### ISSUE TITLE
Issue with regular travis encrypt with three args

### ISSUE THREAD

**Issue by nicosommi** [pwmckenna/node-travis-encrypt#10]
Hello,
I'm getting an error when no user and password is send to the library using it as a module. I created a gist with a test using the example code on the readme. See below

This is the error:
TypeError: callback is not a function
/lib/travis-encrypt.js:64:16

## Steps to reproduce it
```bash
git clone https://gist.github.com/nicosommi/acfcdaaf44590a239bfc
cd acfcdaaf44590a239bfc
npm install
mocha index.js
```

**Comment by rexxars** [comment]
I really want to change the API for this module, to take an options object instead of individual arguments (obviously bumping the major version to indicate the breaking change). Am I allowed to do this, @pwmckenna?

Until then, you'll have to use it like this:
```js
encrypt('pwmckenna/node-travis-encrypt', 'FOO=BAR', undefined, undefined, function(err, result) {
    t.equals(err.message, 'Some key error');
});
```

Key part being 2x `undefined` in the arguments list.

**Comment by pwmckenna** [comment]
@rexxars sorry for the delay. I consider you as much an owner of this project as I am (and lately, more of one). Feel free!

**Comment by rstacruz** [comment]
:+1: the arguments API is silly right now.

**Comment by rexxars** [comment]
Changed the API for this in #19, new version has a more sane API. Closing.
